#!/usr/bin/env bash
# Reproducible PWA app bundles for the fleet.
#
# Declare your PWAs once (pwas.txt) and regenerate real .app launchers on ANY
# Mac — so a migration never leaves "?" placeholders in the Dock again. This is
# the fleet-native answer to Safari's "Add to Dock", which is GUI-only and
# produces an OS-registered app that does not survive Migration Assistant.
#
# Usage:
#   scripts/pwa-apps.sh build                 # build every PWA in pwas.txt
#   scripts/pwa-apps.sh build --pin           # ...and pin each to the Dock (needs dockutil)
#   scripts/pwa-apps.sh build --engine stub   # zero-toolchain engine (no Rust)
#   scripts/pwa-apps.sh list                  # show declared PWAs
#   scripts/pwa-apps.sh doctor                # check toolchain (pake / rust / dockutil)
#
# Engines:
#   pake  (default) — native standalone app via Tauri. Needs Rust + `npm i -g pake-cli`.
#                     Real app process, native notifications/badging. ~5 MB, slow first build.
#   stub            — .app whose launcher opens the URL in a browser's --app mode.
#                     No build toolchain, instant, reuses your logged-in browser profile.
#
# Manifest (pwas.txt) — one PWA per line, blank lines and #comments ignored:
#   Name | https://url | optional/icon.icns   (icon path is relative to the dotfiles root)

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
MANIFEST="${PWA_MANIFEST:-$DOTFILES_DIR/pwas.txt}"
APPS_DIR="$HOME/Applications"
ENGINE="pake"
PIN=0
# Browser used by the `stub` engine. Must support --app mode (Chrome/Brave/Edge; NOT Arc/Safari).
BROWSER="${PWA_BROWSER:-Google Chrome}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; s="${s%"${s##*[![:space:]]}"}"; printf '%s' "$s"; }

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed -E 's/-+/-/g; s/^-//; s/-$//'
}

# Escape XML-significant chars so names like "R&D" produce a valid Info.plist.
xml_escape() {
  local s="$1"
  s="${s//&/&amp;}"; s="${s//</&lt;}"; s="${s//>/&gt;}"; s="${s//\"/&quot;}"; s="${s//\'/&apos;}"
  printf '%s' "$s"
}

# Emit "name<TAB>url<TAB>icon" for each valid manifest line.
read_manifest() {
  if [ ! -f "$MANIFEST" ]; then die "no manifest at $MANIFEST"; fi
  local line name url icon t
  while IFS= read -r line || [ -n "$line" ]; do
    t="$(trim "$line")"
    # Skip blank lines and full-line comments; strip only " #" inline comments so a
    # bare '#' inside a URL (hash-route fragments like https://x/#/inbox) survives.
    case "$t" in ''|'#'*) continue;; esac
    line="${line%% #*}"
    IFS='|' read -r name url icon <<<"$line"
    name="$(trim "${name:-}")"; url="$(trim "${url:-}")"; icon="$(trim "${icon:-}")"
    if [ -z "$name" ] || [ -z "$url" ]; then
      warn "skipping malformed line: $line"; continue
    fi
    printf '%s\t%s\t%s\n' "$name" "$url" "$icon"
  done < "$MANIFEST"
}

# --- stub engine: a .app whose launcher opens the URL in browser --app mode ---
create_stub() {
  local name="$1" url="$2" icon="$3"
  local bin="/Applications/$BROWSER.app/Contents/MacOS/$BROWSER"
  if [ ! -x "$bin" ]; then die "browser not found: $bin (set PWA_BROWSER=\"Brave Browser\" etc.)"; fi
  local app="$APPS_DIR/$name.app"
  rm -rf "$app"
  mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
  local iconkey="" xname
  xname="$(xml_escape "$name")"
  if [ -n "$icon" ] && [ -f "$icon" ]; then
    cp "$icon" "$app/Contents/Resources/icon.icns"
    iconkey='  <key>CFBundleIconFile</key><string>icon</string>'
  fi
  cat > "$app/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>$xname</string>
  <key>CFBundleDisplayName</key><string>$xname</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIdentifier</key><string>com.rh7.pwa.$(slugify "$name")</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
$iconkey
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
</dict></plist>
PLIST
  cat > "$app/Contents/MacOS/launch" <<LAUNCH
#!/bin/sh
# Auto-generated by pwa-apps.sh — opens this PWA in a dedicated browser app window.
exec "$bin" --app="$url" --profile-directory=Default "\$@"
LAUNCH
  chmod +x "$app/Contents/MacOS/launch"
  # Refresh Launch Services + icon cache so the new bundle is recognized immediately.
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$app" >/dev/null 2>&1 || true
  touch "$app"
}

# --- pake engine: native Tauri app ---
ensure_pake() {
  if command -v pake >/dev/null 2>&1; then return 0; fi
  if ! command -v npm >/dev/null 2>&1; then die "npm required to install pake-cli"; fi
  local prefix; prefix="$(npm config get prefix 2>/dev/null || true)"
  # Nix-provided npm defaults its global prefix to the immutable Nix store, so a
  # plain `npm i -g` fails EACCES. Fall back to a user-writable prefix — matching
  # the NPM_CONFIG_PREFIX policy in modules/home/profiles/development.nix — so a
  # fresh Nix Mac works without any manual `npm config`.
  if [ -z "$prefix" ] || [ ! -w "$prefix/lib" ]; then
    prefix="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
    log "npm global prefix not writable — installing pake-cli into $prefix"
    mkdir -p "$prefix/lib" "$prefix/bin"
    PATH="$prefix/bin:$PATH"; export PATH
    npm install -g --prefix "$prefix" pake-cli
  else
    log "installing pake-cli globally (npm)…"
    npm install -g pake-cli
  fi
  if ! command -v pake >/dev/null 2>&1; then
    die "pake-cli installed but 'pake' is not on PATH — add ${prefix}/bin to your PATH"
  fi
}
ensure_rust() {
  if command -v cargo >/dev/null 2>&1; then return 0; fi
  die "Rust not found — pake builds a Tauri app and needs it.
  Install:  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  Or use the zero-toolchain engine:  scripts/pwa-apps.sh build --engine stub"
}
create_pake() {
  local name="$1" url="$2" icon="$3"
  local tmp; tmp="$(mktemp -d)"
  # --targets app: build only the .app. pake's default also builds a .dmg whose
  # bundle_dmg.sh (Finder-automation) is flaky on recent macOS and fails the run
  # AFTER the good .app is produced — so we never ask for the dmg.
  local args=( "$url" --name "$name" --targets app )
  if [ -n "$icon" ] && [ -f "$icon" ]; then args+=( --icon "$icon" ); fi
  ( cd "$tmp" && pake "${args[@]}" ) || warn "pake exited non-zero for $name — checking for a built .app anyway"
  local built
  built="$(/usr/bin/find "$tmp" -maxdepth 2 -name "$name.app" -print -quit 2>/dev/null)"
  if [ -z "$built" ]; then
    # Fallback: pake compiles the .app into its own target dir before copying out.
    local pdir; pdir="$(npm root -g 2>/dev/null)/pake-cli/src-tauri/target"
    built="$(/usr/bin/find "$pdir" -maxdepth 6 -name "$name.app" -type d -print -quit 2>/dev/null)"
  fi
  if [ -z "$built" ]; then rm -rf "$tmp"; warn "pake produced no .app for $name"; return 1; fi
  rm -rf "$APPS_DIR/$name.app"
  cp -R "$built" "$APPS_DIR/$name.app"
  rm -rf "$tmp"
}

pin_dock() {
  local app="$1" label
  label="$(basename "$app" .app)"
  if command -v dockutil >/dev/null 2>&1; then
    # --replacing makes this idempotent: re-running build --pin updates the existing
    # Dock item in place instead of appending a duplicate.
    dockutil --no-restart --add "$app" --replacing "$label" >/dev/null 2>&1 \
      || warn "dockutil failed to pin $label"
  else
    warn "dockutil not installed (brew install dockutil) — not pinning $label"
  fi
}

cmd_build() {
  if [ ! -f "$MANIFEST" ]; then die "no manifest at $MANIFEST"; fi
  mkdir -p "$APPS_DIR"
  if [ "$ENGINE" = "pake" ]; then ensure_rust; ensure_pake; fi
  local name url icon built=0 failed=0
  while IFS=$'\t' read -r name url icon; do
    if [ -n "$icon" ]; then case "$icon" in /*) ;; *) icon="$DOTFILES_DIR/$icon";; esac; fi
    log "[$ENGINE] $name → $url"
    if "create_$ENGINE" "$name" "$url" "$icon"; then
      built=$((built + 1))
      if [ "$PIN" -eq 1 ]; then pin_dock "$APPS_DIR/$name.app"; fi
    else
      warn "failed to build $name"; failed=$((failed + 1))
    fi
  done < <(read_manifest)
  log "built $built app(s) into $APPS_DIR${failed:+ ($failed failed)}"
  if [ "$PIN" -eq 1 ] && command -v dockutil >/dev/null 2>&1; then killall Dock >/dev/null 2>&1 || true; fi
  if [ "$failed" -gt 0 ]; then return 1; fi   # non-zero for automation when any build failed
}

cmd_list() {
  if [ ! -f "$MANIFEST" ]; then die "no manifest at $MANIFEST"; fi
  local name url icon
  while IFS=$'\t' read -r name url icon; do
    printf '  %-24s %s%s\n' "$name" "$url" "${icon:+  [icon: $icon]}"
  done < <(read_manifest)
}

cmd_doctor() {
  printf 'engine default : %s\n' "$ENGINE"
  printf 'manifest       : %s%s\n' "$MANIFEST" "$( [ -f "$MANIFEST" ] && echo '' || echo '  (MISSING)')"
  printf 'pake           : %s\n' "$(command -v pake || echo 'not installed  (npm i -g pake-cli)')"
  printf 'cargo/rust     : %s\n' "$(command -v cargo || echo 'not installed  (needed for pake engine)')"
  printf 'dockutil       : %s\n' "$(command -v dockutil || echo 'not installed  (brew install dockutil; only for --pin)')"
  printf 'stub browser   : %s\n' "/Applications/$BROWSER.app$( [ -d "/Applications/$BROWSER.app" ] && echo '' || echo '  (MISSING)')"
}

main() {
  local cmd="${1:-}"; shift || true
  while [ $# -gt 0 ]; do
    case "$1" in
      --engine) ENGINE="${2:?--engine needs a value}"; shift 2;;
      --engine=*) ENGINE="${1#*=}"; shift;;
      --pin) PIN=1; shift;;
      *) die "unknown option: $1";;
    esac
  done
  case "$cmd" in
    build)  cmd_build ;;
    list)   cmd_list ;;
    doctor) cmd_doctor ;;
    ""|-h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//' ;;
    *) die "unknown command: $cmd (try: build | list | doctor)";;
  esac
}

main "$@"
